apiVersion: batch/v1
kind: Job
metadata:
  namespace: mlflow
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: "mlscience-project"
        # image: "akhuy/mlscience:35653b3"
        # command: ["/bin/sh","-c"]
        # args: ["pip3 install -r requirements.txt && python train.py"]
        env:
          - name: MLFLOW_TRACKING_URI
            value: "http://35.241.233.235/mlflow/"
      restartPolicy: Never