apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: akhuy/mlflow:1.20.2
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: mlflow
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: getambassador.io/v2
kind:  Mapping
metadata:
  name:  mlflow-mapping
  namespace: mlflow
spec:
  prefix: /mlflow/
  service: http://mlflow-service:80