name: Model build
on: [push]

jobs:
  mlflow-run:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: http://35.241.233.235/mlflow/
      GKE_PROJECT: strategic-lens-329311
      GKE_CLUSTER: mlops-hhz-standard-cluster
      GKE_ZONE: europe-west1
      MODEL_NAME: ElasticnetWineModel
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7.9"
      - name: Install mlflow
        run: pip install -r requirements.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # Enable this to deploy your newly created models directly
      # Get the GKE credentials so we can deploy to the cluster
      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          project_id: ${{ env.GKE_PROJECT }}
      - run: |-
          gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"
      - name: Deploy ML Job
        run: |-
          mlflow run ./ --backend kubernetes --backend-config ./backend-config.json